# site name
# 站点名
prefixName: さくら荘その
siteName: 十六夜

# favicon and site master avatar
# 站点的favicon和头像 输入图片路径
#（下面的配置是都是cdn的相对路径，没有cdn请填写完整路径，
# 建议使用jsdeliver搭建一个cdn啦，先去下载我的cdn替换下图片就行了，简单方便~）
favicon: /images/favicon.ico
avatar: /images/favicon.png

# 站点url 
url: https://fate-pdy.github.io/

# 站点介绍（或者说是个人签名）
description: 问题児たちが异世界から来るそうですよ？

# 站点cdn
# cdn: https://cdn.jsdelivr.net/gh/Fate-PDY/cdn@v1.0

# 开启pjax 
pjax: 1

# 1开启
mathjax: 0

# 站点首页的公告信息
notice: 十六夜のさくら荘そは現在開発中...

# 懒加载的加载中图片
lazyloadImg: /images/loading.gif

# 站点菜单配置
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10

# 背景图片 更好的修改
bg:
  - /images/cover/(0).jpg.webp
  - /images/cover/(1).jpg.webp
  - /images/cover/(2).jpg.webp
  - /images/cover/(3).jpg.webp
  - /images/cover/(4).jpg.webp
  - /images/cover/(5).jpg.webp
  - /images/cover/(6).jpg.webp
  - /images/cover/(7).jpg.webp
  - /images/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-grid

# startdash面板 url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/startdash02.png}
  - {url: /, title: Bilibili, desc: 博主没有B站视频, img: /img/startdash/startdash03.png}
  - {url: /, title: 十六夜的万事屋, desc: 技术服务, img: /img/startdash/startdash04.png}



# your site build time or founded date
# 站点建立日期
siteBuildingTime: 01/25/2020

# 社交按钮(social) url, img PC端配置
social:
  github: {url: http://github.com/Fate-PDY, img: /img/social/github1.png}
  # sina: {url: /, img: /img/social/sina.png}
  # wangyiyun: {url: /, img: /img/social/wangyiyun.png}
  # zhihu: {url: /, img: /img/social/zhihu.png}
  # email: {url: /, img: /img/social/email.svg}
  # wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

# 社交按钮(social) url, img 移动端配置
msocial:
  github: {url: http://github.com/Fate-PDY, fa: fa-github, color: 333}
  weibo: {url: /, fa: fa-weibo, color: dd4b39}
  qq: {url: /, fa: fa-qq, color: 25c6fe}

# 赞赏二维码（其中wechatSQ是赞赏单页面的赞赏码图片）
donate:
  # paypal: 
  alipay: /images/donate/AliPayQR.jpg
  wechat: /images/donate/WeChanQR.jpg
  wechatSQ: /images/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

# 左下角aplayer播放器配置 主要改id和server这两项，修改详见[aplayer文档]
aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine评论配置
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

